### ISSUE TITLE
Question: Do your usage of models like IRT, DAS3H, Best-LR include the user feature?

### ISSUE THREAD

**Issue by mdgbayly** [rschmucker/Large-Scale-Knowledge-Tracing#2]
Apologies if this is a newbie question, I'm basically a hobbyist with this stuff, but is there a reason why your models that include a student ability parameter such as IRT, don't appear (at least on the face of it to me!) to use the user ID one-hot feature?

I see that defined as a feature in `feature_preparation.sh` , `one_hot_features.py` etc, but I don't see it used anywhere.

**Comment by mdgbayly** [comment]
I noticed that the https://github.com/theophilee/learner-performance-prediction#logistic-regression repo, also doesn't include the user feature. So I skimmed their paper [When is Deep Learning the Best Approach to Knowledge Tracing](https://files.eric.ed.gov/fulltext/EJ1273917.pdf)? again and saw this in the section 9.1 Limitations.

> Our cross-validation methodology across students does not do justice to Item Response Theory (IRT), as the student ability parameter is never fit 

So maybe that explains why they/you don't include the feature, as student's in the test set would never have a value for ability?

**Comment by rschmucker** [comment]
Exactly, we do not fit a student ability parameter because we assume that the students in the test set are "new users" (i.e., we have no data from them to fit an ability parameter with). You could add the student feature to our existing models for student assessment purposes -- i.e., determine the student ability value which best explains the observed student behaviour in hindsight.
