### ISSUE TITLE
Dataset of Squirrel Ai ElemMath2021

### ISSUE THREAD

**Issue by zhouhq10** [rschmucker/Large-Scale-Knowledge-Tracing#5]
Hi,
Thank you so much for open-source the code and also the comprehensive work. 
I wonder do you plan to also open-source the data of Squirrel Ai ElemMath2021?

**Comment by rschmucker** [comment]
Hello, due to local policy changes we were forced to suspend the sharing of the Squirrel Ai ElemMath2021 dataset and were required to remove it from the DataShop website where it was originally hosted. We still desire to share this data with the research community, but are waiting for clarifications about the China PIPL (Personal Information and Privacy Law) requirements and compliance procedures. The other three datasets we used for our study are still publicly available.
